### ISSUE TITLE
Watermark Padding in resolveNextConversationMessageId

### ISSUE THREAD

**Issue by JimG777** [Samurais/DirectLineApi#5]
Hello,

Thanks for maintaining the module for the DirectLine API, it makes it easy to use.

A couple weeks ago I was able to use the module successfully. However, upon testing today I don't get responses. I found that the resolveNextConversationMessageId() function was never finding a match because of the padding amount. The val.id always had a format like this:

FrURyk0qSIpHOan45TRMHn|0000002

Whereas the data.nextId was like this:

FrURyk0qSIpHOan45TRMHn|000000000000000002

Therefore, we had to adjust the 'leftpad' to 7 instead of 18.

Do you know what is going on?

Thanks,

James

**Comment by Samurais** [comment]
hi, sorry, just got your message. 
how is going with this nextId now?
Can you create a PR for this issue?
